### ISSUE TITLE
Read/Write Dicom image

### ISSUE THREAD

**Issue by ADeane6** [lukestowe1/DicomRead-DicomWrite#4]
A Method/Procedure for reading in an image and write out an image, used as a base for working on images 3368be7caa994f829cdb73ba80132a5218b80c1d

**Comment by ADeane6** [comment]
Read in the image as bytes using java input stream, store in an byte array

**Comment by lukestowe1** [comment]
Need to check header of dicom image normaly around 2000 bytes in size we check this against two arrays 512 or 520 to tell us what size image is. From this we store were the pixels start at the write back to later
